kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: microservices
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6379
        hostPort: 6379
        protocol: TCP
      - containerPort: 5672
        hostPort: 5672
        protocol: TCP
      - containerPort: 15672
        hostPort: 15672
        protocol: TCP
      - containerPort: 30578
        hostPort: 5678
        protocol: TCP
      - containerPort: 32080
        hostPort: 2406
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
